# Setup
title:               Going Work
tagline:             'please help us'
description:         ''
url:                 https://dyong0.github.io
baseurl:             'https://dyong0.github.io'
paginate:            20

# About/contact
author:
  name:              dyong
  url:               https://dyong0.github.io
  email:             likedyong@gmail.com

# Custom vars
version:             1.0.0

gems: [jekyll-paginate, jekyll-watch, jekyll-assets]
